language: ruby
rvm:
  - ruby-head
  - 2.4
  - 2.3
  - 2.2
  - 2.1
gemfile:
  - Gemfile
  - gemfiles/activerecord_5.gemfile
  - gemfiles/activerecord_4.gemfile
matrix:
  exclude:
  - rvm: 2.1
    gemfile: gemfiles/activerecord_5.gemfile
script: "bundle exec rake spec"
